ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducción y Objetivos

La empresa de desarrollo de juegos **Micrati** ha decidido apostar por el  desarrollar un juego en formato webapp basado en el "Juego Y", que tendrá el nombre **YOVI**. Estamos ante un juego de mesa de estrategia de dos jugadores que transformaremos y modificaremos para que se pueda jugar con el ordenador.

=== Resumen de Requisitos

El sistema debe cumplir con las siguientes funcionalidades principales:

* [cite_start]**Frontend Web:** Permitir a las personas jugar partidas del juego Y a través del navegador.
* **Versión Clásica:** Implementar el juego contra la máquina con un tamaño de tablero variable.
* **Estrategias de IA:** El juego contra la computadora debe implementar más de una estrategia seleccionable.
* **Niveles de Dificultad:** El jugador podrá elegir el nivel de dificultad de las estrategias.
* **Despliegue:** La aplicación deberá estar desplegada y ser accesible de forma pública en la Web.
* **Gestión de Usuarios:** Registro en el sistema y consulta de histórico (partidas, estadísticas, etc.).
* **API Documentada:** Una interfaz que permita a bots interactuar con la gestión de usuarios y partidas.
* [cite_start]**Modo Bot:** El API expondrá un método `play` con notación YEN para que un bot juegue contra la aplicación.

=== Objetivos de Calidad

[options="header",cols="1,3"]
|===
|Objetivo|Descripción
|**Funcionalidad**|El sistema cumple con las necesidades esperadas de juego y gestión.
|**Mantenibilidad**|El sistema se puede adaptar y/o modificar fácilmente ante cambios en el entorno o requisitos.
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Rol|Nombre / Contacto|Expectativas

.4+|**Equipo de desarrolladores** | Iyán Iglesias Ibaseta (https://github.com/iyaniglesias) 
.4+|Desarrollar YOVI con las herramientas adecuadas, cumpliendo los requisitos y asegurando que permita a los usuarios competir y conseguir una puntuación en base a la partida jugada.

| Jimena Vázquez Suárez (https://github.com/JimenaVazquez)
| Sara Naredo Fernández (https://github.com/saranaredo)
| Carolina González García (https://github.com/arigl-gh)

|**Compañía** | Micrati 
| Cumplir y dictar los requisitos del juego para presentar la aplicación.

|**Usuarios** | Futuros usuarios del juego YOVI 
| Aprender y disfrutar del juego YOVI, logrando entretenimiento, competición sana y ocio de la aplicación.

.2+|**Equipo de supervisión** | José Emilio Labra Gayo 
.2+|Evaluar el resultado y aconsejar durante el desarrollo de la aplicación.

| Celia Melendi Lavandera 
|===